services:
  db:
    container_name: MSSQL
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: "dbPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
# connection string 
# "Server=localhost,1433;Database=master;User Id=sa;Password=dbPassword123!;TrustServerCertificate=true"